### ISSUE TITLE
fails to triangulate

### ISSUE THREAD

**Issue by davidm** [Yonaba/delaunay#1]
local DEL = dofile 'delaunay.lua'
local points = {DEL.Point(0,0,0), DEL.Point(200,1,0), DEL.Point(400,0,0), DEL.Point(300,5,0)}
local triangles = DEL.triangulate(unpack(points))
print(#triangles)  -- outputs 0 (wrong)
for _,tri in ipairs(triangles) do print(tri) end

In comparison, here's what GNU Octave reports:

octave:1> x=[0, 200, 400, 300];
octave:2> y=[0, 1, 0, 5];
octave:3> T = delaunay (x, y);
octave:4> T
T =

   2   3   1
   2   4   1
   2   4   3

**Comment by Yonaba** [comment]
Hi, @davidm,

As of commit fd8f63b, this is now fixed.
Sorry for the late answer.
Thanks!
